[package]
name = "min-mpv"
version = "0.1.0"
edition = "2024"
rust-version = "1.92"

[dependencies]
eframe = { version = "0.35", default-features = false, features = ["glow", "default_fonts", "persistence"] }
egui-sharkplayer = { version = "0.5", default-features = false }
rfd = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

statig = { version = "0.4", default-features = false, features = ["macro"] }
axum = "0.8"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "sync", "time", "fs"] }
reqwest = { version = "0.13", features = ["stream"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
chrono = "0.4"
dirs = "5"
dotenvy = "0.15"
grammers-client = "0.10"
grammers-session = "0.10"
anyhow = "1"
rangemap = "1.7"
urlencoding = "2"
